export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const SET_PRODUCTS_REQUEST = "SET_PRODUCTS_REQUEST";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const ADD_ITEM_TO_ORDER = "ADD_ITEM_TO_ORDER";
export const REMOVE_ITEM_FROM_ORDER = "REMOVE_ITEM_FROM_ORDER";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_ERROR = "SET_ORDER_ERROR";
