export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const SET_PRODUCTS_REQUEST = "SET_PRODUCTS_REQUEST";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_ERROR = "SET_ORDER_ERROR";

export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
